#!/usr/bin/env bash
#
# bootstrap.sh -- turn a bare EPICS host into one that can run ecmccfg scripts.
#
# Three jobs, in order:
#   1. generate RELEASE.local (EPICS modules) and CONFIG_SITE.local (external deps)
#   2. stage ecmccfg into a flat install    (runtime script/template paths)
#   3. build the training IOC
#   4. generate iocBoot/.../ecmcPaths.cmd   (the env contract replacing require)
#
# Everything it writes is derived from site.conf and is gitignored, so this
# repository stays portable while your host paths stay yours.
#
# Safe to re-run.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/.." && pwd)"
app="$here/ecmcTrainingApp"

if [[ ! -f "$repo/site.conf" ]]; then
  echo "ERROR: $repo/site.conf not found." >&2
  echo "       cp $repo/site.conf.example $repo/site.conf and edit it." >&2
  exit 1
fi
# shellcheck disable=SC1091
source "$repo/site.conf"

: "${EPICS_BASE:?EPICS_BASE must be set in site.conf}"
: "${EPICS_MODULES:?EPICS_MODULES must be set in site.conf}"
: "${ECMC_SRC:?ECMC_SRC must be set in site.conf}"
: "${ECMCCFG_SRC:?ECMCCFG_SRC must be set in site.conf}"
ETHERLAB="${ETHERLAB:-/opt/etherlab}"
: "${DEPS_DIR:?DEPS_DIR must be set in site.conf}"

# Source dependencies live at $DEPS_DIR/<package>/<version>, so the version
# comes from deps.conf rather than being hardcoded here.
# shellcheck disable=SC1091
source "$here/deps-lib.sh"
RUCKIG_DIR="$(dep_dir ruckig)"
if [[ -z "$RUCKIG_DIR" ]]; then
  echo "ERROR: ruckig is not declared in 00-bootstrap/deps.conf" >&2
  exit 1
fi
STAGE="${ECMCCFG_STAGE:-$repo/stage/ecmccfg}"

if [[ -z "${EPICS_HOST_ARCH:-}" ]]; then
  if [[ -x "$EPICS_BASE/startup/EpicsHostArch" ]]; then
    EPICS_HOST_ARCH="$("$EPICS_BASE/startup/EpicsHostArch")"
  elif [[ -f "$EPICS_BASE/startup/EpicsHostArch.pl" ]]; then
    EPICS_HOST_ARCH="$(perl "$EPICS_BASE/startup/EpicsHostArch.pl")"
  else
    echo "ERROR: cannot determine EPICS_HOST_ARCH; set it in site.conf." >&2
    exit 1
  fi
fi
export EPICS_HOST_ARCH

echo "==> bootstrap"
echo "    EPICS_BASE      : $EPICS_BASE"
echo "    EPICS_MODULES   : $EPICS_MODULES"
echo "    EPICS_HOST_ARCH : $EPICS_HOST_ARCH"
echo "    DEPS_DIR        : $DEPS_DIR"
echo "    ruckig          : $RUCKIG_DIR"
echo

# ---------------------------------------------------------------------------
# 1. build-time dependency paths
#
# This is the file that a require/e3 site does NOT have: there, dependencies
# are resolved at runtime from a .dep file.  Here they are resolved at build
# time by the standard EPICS mechanism.  See ../appendix-require.md.
# ---------------------------------------------------------------------------
echo "==> writing $app/configure/RELEASE.local"
cat > "$app/configure/RELEASE.local" <<EOF
# GENERATED by 00-bootstrap/bootstrap.sh from site.conf -- do not edit.
# Re-run bootstrap.sh after changing site.conf.
#
# EPICS support modules only. External libraries are in CONFIG_SITE.local.

# Module versions come from site.conf. Following the PCDS convention of naming
# them <MODULE>_MODULE_VERSION so scripts can extract them.
ASYN_MODULE_VERSION  = ${ASYN_MODULE_VERSION:-}
MOTOR_MODULE_VERSION = ${MOTOR_MODULE_VERSION:-}
ECMC_MODULE_VERSION  = ${ECMC_MODULE_VERSION:-}

SUPPORT    = $EPICS_MODULES

ASYN       = $(module_dir asyn)
MOTOR      = $(module_dir motor)

# ECMC points at the built module (for libecmc, its dbd, and libexprtkSupport)
ECMC       = $(module_dir ecmc)

# Fail early and by name, rather than leaving CHECK_RELEASE to report a path
# with no indication of which module it belongs to.
ifeq (\$(wildcard \$(ASYN)),)
\$(error ASYN path not found: \$(ASYN))
endif
ifeq (\$(wildcard \$(MOTOR)),)
\$(error MOTOR path not found: \$(MOTOR))
endif
ifeq (\$(wildcard \$(ECMC)),)
\$(error ECMC path not found: \$(ECMC))
endif

# EPICS_BASE last so it appears last in the DB, DBD, INCLUDE and LIB search paths
EPICS_BASE = $EPICS_BASE
EOF

echo "==> writing $app/configure/CONFIG_SITE.local"
cat > "$app/configure/CONFIG_SITE.local" <<EOF
# GENERATED by 00-bootstrap/bootstrap.sh from site.conf -- do not edit.
# Re-run bootstrap.sh after changing site.conf.
#
# Non-EPICS dependencies: ordinary libraries and file trees with no EPICS
# module structure, so they belong here rather than in RELEASE.

# Etherlab EtherCAT master: autotools install prefix (ecrt.h, libethercat)
ETHERLAB   = $ETHERLAB

# ruckig: CMake project, built by build-deps.sh; the rpath points into build/
RUCKIG     = $RUCKIG_DIR

# ecmccfg SOURCE checkout -- only to compile ECATtimestamp.cpp.
# The staged install is a runtime concern, handled by ecmcPaths.cmd.
ECMCCFG    = $ECMCCFG_SRC
EOF

# ---------------------------------------------------------------------------
# 2. runtime script/template paths (the flattened ecmccfg install)
# ---------------------------------------------------------------------------
echo
"$here/stage-ecmccfg.sh"
echo
"$here/stage-ecmccomp.sh"

# ---------------------------------------------------------------------------
# 2b. patch the upstream checkouts
#
# Normally they are read-only. The exception is ecmc 11.0.x, which does not
# compile against upstream motor. See ../patches/README.md.
# ---------------------------------------------------------------------------
if [[ -d "$repo/patches" ]]; then
  echo
  "$here/apply-patches.sh"
fi

# ---------------------------------------------------------------------------
# 3. build the IOC
# ---------------------------------------------------------------------------
echo "==> building the training IOC"
make -C "$app" "$@"

ioc_bin="$app/bin/$EPICS_HOST_ARCH/ecmcTrainingIoc"
if [[ ! -x "$ioc_bin" ]]; then
  echo "ERROR: build finished but $ioc_bin is missing." >&2
  exit 1
fi
echo "    built $ioc_bin"

# Arch-neutral symlink for the st.cmd shebangs. Sites name the host arch
# differently -- upstream auto-detection says linux-x86_64, PCDS builds are
# rhel9-x86_64 -- so no committed file may hardcode it.
ln -sfn "$EPICS_HOST_ARCH" "$app/bin/current"
echo "    bin/current -> $EPICS_HOST_ARCH"

# ---------------------------------------------------------------------------
# 4. the env contract that replaces `require`
#
# ecmccfg needs <module>_DIR variables and a database search path.  A
# require-based IOC gets these as a side effect of loading each module; we set
# them explicitly.  requireStub.cpp verifies they are right.
# ---------------------------------------------------------------------------
boot="$app/iocBoot/ecmcTrainingIoc"
echo "==> writing $boot/ecmcPaths.cmd"

# ecmccomp is optional -- only phases using component-configured hardware need
# it (phase 03, the EL7062). Emit the variable only when it is actually staged,
# so requireStub's check stays meaningful rather than pointing at a stub path.
comp_stage="${ECMCCOMP_STAGE:-$repo/stage/ecmccomp}"
if [[ -f "$comp_stage/applyComponent.cmd" ]]; then
  comp_line="epicsEnvSet(\"ecmccomp_DIR\",          \"$comp_stage/\")"
else
  comp_line="# ecmccomp not staged -- set ECMCCOMP_SRC in site.conf if phase 03 needs it"
fi

db_path="$STAGE/db"
db_path="$db_path:$ECMC_SRC/devEcmcSup/logic/db"   # cpp_logic templates (phase 04)
[[ -d "$comp_stage/db" ]] && db_path="$db_path:$comp_stage/db"
db_path="$db_path:$EPICS_MODULES/motor/db"
db_path="$db_path:$EPICS_MODULES/asyn/db"
db_path="$db_path:$EPICS_BASE/db"

write_paths_file() {
  cat > "$1" <<EOF
# GENERATED by 00-bootstrap/bootstrap.sh from site.conf -- do not edit.
#
# This file is what a require-based IOC would get for free when it ran
# "require ecmc" / "require ecmccfg".  We set it explicitly instead.

# Trailing slash on ecmccfg_DIR is MANDATORY: ecmccfg builds paths by direct
# concatenation, e.g. \${ecmccfg_DIR}addSlave.cmd
epicsEnvSet("ecmccfg_DIR",           "$STAGE/")
epicsEnvSet("ecmccfg_DB",            "$STAGE/db")
epicsEnvSet("ecmc_DIR",              "$EPICS_MODULES/ecmc")
$comp_line

# Templates are loaded by bare filename, so every directory holding one must
# be on this path.
epicsEnvSet("EPICS_DB_INCLUDE_PATH", "$db_path")
EOF
}

# The phase-00 smoke-test IOC reads it from its own boot directory...
write_paths_file "$boot/ecmcPaths.cmd"
# ...and every later phase reads it from the repository root as "< ../ecmcPaths.cmd",
# so each phase directory holds only its own st.cmd and config.
write_paths_file "$repo/ecmcPaths.cmd"
echo "    wrote $repo/ecmcPaths.cmd (used by phases 02+)"

echo
echo "==> bootstrap complete"
echo
echo "    Verify with:"
echo "        cd $boot && ./st.cmd"
echo "    Expected result is described in 00-bootstrap/VERIFY.md"
echo
