#!/usr/bin/env bash
#
# bootstrap.sh -- turn a bare EPICS host into one that can run ecmccfg scripts.
#
# Three jobs, in order:
#   1. generate configure/RELEASE.local     (build-time module paths)
#   2. stage ecmccfg into a flat install    (runtime script/template paths)
#   3. build the training IOC
#   4. generate iocBoot/.../ecmcPaths.cmd   (the env contract replacing require)
#
# Everything it writes is derived from site.conf and is gitignored, so this
# repository stays portable while your host paths stay yours.
#
# Safe to re-run.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/.." && pwd)"
app="$here/ecmcTrainingApp"

if [[ ! -f "$repo/site.conf" ]]; then
  echo "ERROR: $repo/site.conf not found." >&2
  echo "       cp $repo/site.conf.example $repo/site.conf and edit it." >&2
  exit 1
fi
# shellcheck disable=SC1091
source "$repo/site.conf"

: "${EPICS_BASE:?EPICS_BASE must be set in site.conf}"
: "${EPICS_MODULES:?EPICS_MODULES must be set in site.conf}"
: "${ECMC_SRC:?ECMC_SRC must be set in site.conf}"
: "${ECMCCFG_SRC:?ECMCCFG_SRC must be set in site.conf}"
ETHERLAB="${ETHERLAB:-/opt/etherlab}"
STAGE="${ECMCCFG_STAGE:-$repo/stage/ecmccfg}"

if [[ -z "${EPICS_HOST_ARCH:-}" ]]; then
  if [[ -x "$EPICS_BASE/startup/EpicsHostArch" ]]; then
    EPICS_HOST_ARCH="$("$EPICS_BASE/startup/EpicsHostArch")"
  elif [[ -f "$EPICS_BASE/startup/EpicsHostArch.pl" ]]; then
    EPICS_HOST_ARCH="$(perl "$EPICS_BASE/startup/EpicsHostArch.pl")"
  else
    echo "ERROR: cannot determine EPICS_HOST_ARCH; set it in site.conf." >&2
    exit 1
  fi
fi
export EPICS_HOST_ARCH

echo "==> bootstrap"
echo "    EPICS_BASE      : $EPICS_BASE"
echo "    EPICS_MODULES   : $EPICS_MODULES"
echo "    EPICS_HOST_ARCH : $EPICS_HOST_ARCH"
echo

# ---------------------------------------------------------------------------
# 1. build-time dependency paths
#
# This is the file that a require/e3 site does NOT have: there, dependencies
# are resolved at runtime from a .dep file.  Here they are resolved at build
# time by the standard EPICS mechanism.  See ../appendix-require.md.
# ---------------------------------------------------------------------------
echo "==> writing $app/configure/RELEASE.local"
cat > "$app/configure/RELEASE.local" <<EOF
# GENERATED by 00-bootstrap/bootstrap.sh from site.conf -- do not edit.
# Re-run bootstrap.sh after changing site.conf.

SUPPORT    = $EPICS_MODULES

ASYN       = $EPICS_MODULES/asyn
MOTOR      = $EPICS_MODULES/motor
RUCKIG     = $EPICS_MODULES/ruckig

# ECMC points at the built module (for libecmc and its dbd)
ECMC       = $EPICS_MODULES/ecmc

# exprtkSupport lives inside the ecmc source tree
EXPRTK     = $ECMC_SRC/exprtkSupport

# ECMCCFG points at the SOURCE checkout, not the staged install:
# it is used only to compile ECATtimestamp.cpp into this IOC.
ECMCCFG    = $ECMCCFG_SRC

ETHERLAB   = $ETHERLAB

EPICS_BASE = $EPICS_BASE
EOF

# ---------------------------------------------------------------------------
# 2. runtime script/template paths (the flattened ecmccfg install)
# ---------------------------------------------------------------------------
echo
"$here/stage-ecmccfg.sh"

# ---------------------------------------------------------------------------
# 3. build the IOC
# ---------------------------------------------------------------------------
echo "==> building the training IOC"
make -C "$app" "$@"

ioc_bin="$app/bin/$EPICS_HOST_ARCH/ecmcTrainingIoc"
if [[ ! -x "$ioc_bin" ]]; then
  echo "ERROR: build finished but $ioc_bin is missing." >&2
  exit 1
fi
echo "    built $ioc_bin"

# ---------------------------------------------------------------------------
# 4. the env contract that replaces `require`
#
# ecmccfg needs <module>_DIR variables and a database search path.  A
# require-based IOC gets these as a side effect of loading each module; we set
# them explicitly.  requireStub.cpp verifies they are right.
# ---------------------------------------------------------------------------
boot="$app/iocBoot/ecmcTrainingIoc"
echo "==> writing $boot/ecmcPaths.cmd"

db_path="$STAGE/db"
db_path="$db_path:$ECMC_SRC/devEcmcSup/logic/db"   # cpp_logic templates (phase 04)
db_path="$db_path:$EPICS_MODULES/motor/db"
db_path="$db_path:$EPICS_MODULES/asyn/db"
db_path="$db_path:$EPICS_BASE/db"

cat > "$boot/ecmcPaths.cmd" <<EOF
# GENERATED by 00-bootstrap/bootstrap.sh from site.conf -- do not edit.
#
# This file is what a require-based IOC would get for free when it ran
# "require ecmc" / "require ecmccfg".  We set it explicitly instead.

# Trailing slash on ecmccfg_DIR is MANDATORY: ecmccfg builds paths by direct
# concatenation, e.g. \${ecmccfg_DIR}addSlave.cmd
epicsEnvSet("ecmccfg_DIR",           "$STAGE/")
epicsEnvSet("ecmccfg_DB",            "$STAGE/db")
epicsEnvSet("ecmc_DIR",              "$EPICS_MODULES/ecmc")

# Templates are loaded by bare filename, so every directory holding one must
# be on this path.
epicsEnvSet("EPICS_DB_INCLUDE_PATH", "$db_path")
EOF

echo
echo "==> bootstrap complete"
echo
echo "    Verify with:"
echo "        cd $boot && ./st.cmd"
echo "    Expected result is described in 00-bootstrap/VERIFY.md"
echo
