#!../00-bootstrap/ecmcTrainingApp/bin/current/ecmcTrainingIoc
#
# Phase 02 -- temperature DAQ IOC.
#
# Reads two PT100 channels from a Beckhoff EL3202-0010 and publishes them as
# EPICS ai records in degrees Celsius.
#
# !! REQUIRES AN ANALOG INPUT TERMINAL THAT THE TRAINING CRATE DOES NOT HAVE. !!
# The crate is EK1101 + EL5042 + EL7062-0000. This script will fail at
# addSlave.cmd for the EL3202-0010, because that terminal is not on the bus.
# Kept ready for when one is added -- then set TEMP_POS and TEMP_HW.
# See README.md.
#
# Positions default to the reference crate. Override from your own crate.md:
#   ./st.cmd -m TEMP_POS=5
# or edit the defaults below.
#
# bin/current is a symlink to bin/$EPICS_HOST_ARCH, created by bootstrap.sh.

# ---------------------------------------------------------------------------
# Site paths -- generated by 00-bootstrap/bootstrap.sh from site.conf.
# Supplies ecmccfg_DIR, ecmc_DIR and EPICS_DB_INCLUDE_PATH.
# ---------------------------------------------------------------------------
< ../ecmcPaths.cmd

epicsEnvSet("IOC",          "$(IOC=TRAIN-DAQ)")
epicsEnvSet("SCRIPTEXEC",   "iocshLoad")
epicsEnvSet("ECMCCFG_INIT", "")

# Verified by requireStub.cpp, not loaded. See ../appendix-require.md
require ecmccfg "11.0.8"

# ---------------------------------------------------------------------------
# MODE=DAQ -- data acquisition only.
#
#   * no axis objects, no motor record controller
#   * EPICS record update rate follows EC_RATE rather than being pinned to 10 ms
#     as it is in FULL mode
#
# Use DAQ whenever an IOC has no motion. It is a smaller surface to reason about
# and it samples faster.
# ---------------------------------------------------------------------------
$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=11.0.8,MODE=DAQ,EC_RATE=$(EC_RATE=1000)"

# ---------------------------------------------------------------------------
# 1. Declare the bus
#
# Slave IDs are PHYSICAL BUS POSITIONS from your crate.md -- cable order, not
# identity. Each addSlave.cmd resolves ${ecmccfg_DIR}ecmc<HW_DESC>.cmd, which
# declares the PDO mapping and verifies vendor/product ID against the terminal
# actually present. A mismatch aborts startup, by design.
# ---------------------------------------------------------------------------
$(SCRIPTEXEC) ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(COUPLER_POS=0), HW_DESC=$(COUPLER_HW=EK1100)"
$(SCRIPTEXEC) ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(TEMP_POS=3),    HW_DESC=$(TEMP_HW=EL3202-0010)"

# ---------------------------------------------------------------------------
# 2. Configure the sensors -- SDO, written once at startup
#
# This is the PDO/SDO distinction in practice. Everything below writes the
# terminal's object dictionary: what kind of sensor is attached, wiring, filter.
# The measured VALUE is not here -- that is cyclic PDO data, mapped in step 1.
#
# The sensor scripts address channels through ECMC_EC_SDO_INDEX:
#   channel 1 -> 0x8000     channel 2 -> 0x8010     (channel n -> 0x80n0)
# and act on the slave named by ECMC_EC_SLAVE_NUM.
# ---------------------------------------------------------------------------
epicsEnvSet("ECMC_EC_SLAVE_NUM", "$(TEMP_POS=3)")

# Common settings -- filter frequency, applies to all channels (50 Hz default)
$(SCRIPTEXEC) ${ecmccfg_DIR}ecmcEL32XX-Sensor-PT100-common.cmd

# Channel 1: S+S Regeltechnik HTF50, PT100, two-wire, 1.5 m of 0.25 mm2 cable.
# The script sets RTD element (0x80n0:19 = 0 -> Pt100), connection technology
# (0x80n0:1A = 0 -> two wire) and supply-line resistance compensation
# (0x80n0:1B = 3 -> 0.1 ohm). Read it before running it -- it is the clearest
# worked example of SDO configuration in the whole framework.
epicsEnvSet("ECMC_EC_SDO_INDEX", "0x8000")
$(SCRIPTEXEC) ${ecmccfg_DIR}ecmcEL3202-0010-Sensor-chX_S+S_RegelTechnik_HTF50_PT100.cmd

# Channel 2: same sensor type
epicsEnvSet("ECMC_EC_SDO_INDEX", "0x8010")
$(SCRIPTEXEC) ${ecmccfg_DIR}ecmcEL3202-0010-Sensor-chX_S+S_RegelTechnik_HTF50_PT100.cmd

# ---------------------------------------------------------------------------
# 3. Apply -- build the process image
#
# Until now everything has been declaration. This hands the configuration to the
# master, which computes each entry's offset in the cyclic datagram.
# Nothing may be added to the bus after this point.
# ---------------------------------------------------------------------------
$(SCRIPTEXEC) ${ecmccfg_DIR}applyConfig.cmd

# ---------------------------------------------------------------------------
# 4. Diagnostics
# ---------------------------------------------------------------------------
ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
# Tolerate 100 consecutive failed cycles before declaring the bus bad.
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

# ---------------------------------------------------------------------------
# 5. Go active
#
# setAppMode.cmd validates the configuration, loads the EtherCAT diagnostic
# records, starts the realtime thread (Cfg.SetAppMode(1)) and waits ~2 s for the
# bus to stabilise. Slaves should reach OP during this step.
# ---------------------------------------------------------------------------
$(SCRIPTEXEC) ${ecmccfg_DIR}setAppMode.cmd

iocInit()

# Uncomment while learning: lists every PV this IOC created.
#dbl > pvs.log
