#!../../bin/linux-x86_64/ecmcTrainingIoc
#
# Phase 0 smoke test: start ecmc with NO EtherCAT hardware.
#
# This proves the whole bootstrap works -- the IOC binary links ecmc, the
# staged ecmccfg is reachable, the realtime thread starts -- without depending
# on the crate being powered or cabled.  Nothing later in the course is
# meaningful until this runs clean.
#
# If your EPICS_HOST_ARCH is not linux-x86_64, fix the shebang above.

# ---------------------------------------------------------------------------
# Site paths. Generated by 00-bootstrap/bootstrap.sh from site.conf.
# This is the block that replaces `require` -- see ../../../../appendix-require.md
# ---------------------------------------------------------------------------
< ecmcPaths.cmd

epicsEnvSet("IOC",          "$(IOC=TRAIN-BOOTSTRAP)")

# ecmccfg dispatches nested scripts through this. iocshLoad is EPICS base
# native; PSI sites use runScript instead.
epicsEnvSet("SCRIPTEXEC",   "iocshLoad")

# At ESS/PSI, `require ecmccfg` auto-runs startup.cmd. We call it ourselves,
# so this must stay empty.
epicsEnvSet("ECMCCFG_INIT", "")

# ---------------------------------------------------------------------------
# In an upstream IOC this line LOADS ecmccfg at runtime. Here, requireStub.cpp
# turns it into an assertion that ecmccfg_DIR points at a real staged install.
# Keeping the line means upstream examples stay copy-pasteable.
# ---------------------------------------------------------------------------
require ecmccfg "$(ECMCCFG_VER=staged-local)"

# ---------------------------------------------------------------------------
# MASTER_ID=-1 runs ecmc master-less: no EtherCAT master is opened, so this
# works on a host with no bus, no slaves, and no ethercat kernel module.
# startup.cmd internally calls `require ecmc`, which the stub also verifies.
# ---------------------------------------------------------------------------
$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=$(ECMC_VER=11.0.8),MASTER_ID=-1,EC_RATE=1000"

# Go active: starts the ecmc realtime thread. Without a master it simply
# cycles doing nothing, which is exactly what we want to observe.
$(SCRIPTEXEC) ${ecmccfg_DIR}setAppMode.cmd

iocInit()

# Print the ecmc object tree. With no hardware configured this is short, but
# it proves the ecmc side of the IOC is alive and introspectable.
ecmcReport 1
